######################################################################
# Automatically generated by qmake (3.0) So. Okt. 23 23:20:45 2016
######################################################################

TEMPLATE = app
TARGET = SceneEditor
INCLUDEPATH += .

QT += gui core widgets opengl

# Input
SOURCES += main.cpp MainWindow.cpp MenuBar.cpp ObjectBrowser.cpp PropertiesWidget.cpp
HEADERS += MainWindow.h MenuBar.h ObjectBrowser.h PropertiesWidget.h
